zenigo:
  cors:
    url: ${FRONT_END_URL}
  auth:
    jwt:
      secret: ${JWT_SECRET}
      algorithm: HS512
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: nest-gateway-v1
              uri: ${NEST_GATEWAY_V1_URI}
              predicates:
               - Path=/v1/**