logging:
  level:
    org.springframework.security: TRACE
zenigo:
  cors:
    url: ${FRONT_END_URL}
  auth:
    jwt:
      secret: ${JWT_SECRET}
      algorithm: HS256
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origin-patterns:
                  - ${FRONT_END_URL}
                allowed-headers:
                  - Authorization
                  - Content-Type
                allowed-methods:
                  - GET
                  - PUT
                  - POST
                  - DELETE
                  - OPTIONS
                allow-credentials: true
          routes:
            - id: nest-gateway-v1
              uri: ${NEST_GATEWAY_V1_URI}
              predicates:
               - Path=/v1/**