# Default values for nestjs-microservices
# This is a YAML-formatted file.

# Service configuration
service:
  name: api-gateway  # Default service name
  type: ClusterIP
  port: 8000
  targetPort: 8000

# Image configuration
image:
  repository: your-registry/nestjs-microservices
  pullPolicy: IfNotPresent
  tag: "0.0.1"

# Deployment configuration
replicaCount: 1

# Resource limits and requests
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Node selector, tolerations, and affinity
nodeSelector: {}
tolerations: []
affinity: {}

# Pod security context
podSecurityContext:
  fsGroup: 1000

# Container security context
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
    - ALL

# Environment variables
env:
  NODE_ENV: production
  PORT: "8000"

# Additional environment variables from ConfigMap or Secret
envFrom: []
# Example:
# envFrom:
#   - configMapRef:
#       name: app-config
#   - secretRef:
#       name: app-secrets

# Liveness and readiness probes
livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# Service Account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod Disruption Budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1
  # maxUnavailable: 1

# Horizontal Pod Autoscaler
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional labels
labels: {}

# Additional annotations
annotations: {}

# Volume mounts (if needed for Prisma or other files)
volumeMounts: []
# Example:
# volumeMounts:
#   - name: prisma-config
#     mountPath: /app/prisma
#     readOnly: true

# Volumes
volumes: []
# Example:
# volumes:
#   - name: prisma-config
#     configMap:
#       name: prisma-config