# Values for Feature Flags Service
service:
  name: feature-flags-service
  type: ClusterIP
  port: 8000
  targetPort: 8000

replicaCount: 1

env:
  NODE_ENV: production
  PORT: "8000"
  DATABASE_URL: "postgresql://username:password@postgres:5432/feature_flags_db"